name: mymovie
description: My Movie Diary


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.21.0
  get_it: ^1.0.3
  flutter_kakao_login: ^0.0.8
  google_sign_in: 3.2.4
  firebase_auth: 0.7.0
  cloud_firestore: 0.8.2+3
  keyboard_visibility: 0.5.2
  http: ^0.12.0+1
  flutter_bloc: ^0.9.0
  html: ^0.13.4+1
  cached_network_image: ^0.7.0
  auto_size_text: ^1.1.1
  sqflite: ^1.1.0
  flutter_inappbrowser: 0.6.0
  carousel_slider: ^1.3.0
  smooth_star_rating: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/images/kakao.png
    - assets/images/google.png
    - assets/images/fantasy.jpg
    - assets/images/cinema.jpg

    - assets/images/ironman.jpg
    - assets/images/abouttime.jpg
    - assets/images/spiderman.jpg
  fonts:
  - family: Chosunilbo_myungjo
    fonts:
      - asset: assets/fonts/chosun.ttf
  - family: hanna
    fonts:
      - asset: assets/fonts/hanna.ttf